# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StackOverflowList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StackOverflowList
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'StackOverflowListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StackOverflowListUITests' do
    # Pods for testing
  end

end
